version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: development.dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - db
    env_file: ".env"
    develop:
      watch:
        - action: sync+restart
          path: .
          target: /app

  db:
    image: postgres
    container_name: db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: docker
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
