name: Mirror to Gitea

on: [push]

jobs:
  mirror:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout GitHub repository
        uses: actions/checkout@v3

      - name: Push to Gitea (Mirror)
        run: |
          git fetch --unshallow
          git remote add gitea https://samuellando:${{ secrets.GITEA_ACCESS_TOKEN }}@git.zelda.samuellando.com/samuellando/personalWebsite.git
          git push --all gitea --force
          git push --tags gitea --force
